# TODO convert to Travis/Coveralls or similar

test:
  stage: test
  image: $registry/$tag
  script:
    - ls
    - pytest --cov=cmdstanpy --cov-report=term --cov-report=html -n 2 cmdstanpy/tests.py
  artifacts:
    paths:
    - htmlcov/
    - "*.png"

# TODO convert to script or other for e.g. automatic deploy tags to PyPI
release_pypi:
  stage: deploy
  image: $registry/$tag
  only:
    - tags
  script:
    - python setup.py sdist bdist_wheel
    - twine upload -u $TWINE_USERNAME2 -p $TWINE_PASSWORD2 dist/*
