language: python

python:
  - "2.7"
  - "3.6"

cache:
  directories:
  - cmdstan
  - $HOME/.cache/pip

install:
  - dev/make_cmdstan.sh
  - pip install -r requirements.txt
  - pip install flake8 pytest


script:
  - flake8 cmdstanpy
  - CMDSTAN=$PWD/cmdstan pytest cmdstanpy/tests.py