dist: xenial

language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install flake8 pytest
  - ./make_cmdstan.sh

after install:

script:
  - flake8 --extend-ignore=E127,E201,E202,E203,E231,E252,E999,F841 cmdstanpy
  - pytest test
