dist: xenial

language: python

python:
  - "3.6"

cache:
  directories:
  - $HOME/.cmdstanpy

install:
  - pip install -r requirements.txt
  - pip install flake8 pytest
  - python cmdstanpy/install_cmdstan.py

after install:

script:
  - flake8 --extend-ignore=E127,E201,E202,E203,E231,E252,E266,E402,E999,F401,F841,W503,W605 --max-line-length=80 cmdstanpy
  - pytest test
