dist: xenial

language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install flake8 pytest
  - travis_retry ./bin/install_cmdstan

after install:

script:
  - flake8 --extend-ignore=E127,E201,E202,E203,E231,E252,E266,E402,E999,F401,F841,W503,W605 --max-line-length=80 cmdstanpy
  - pytest test
