name: CmdStanPy

on:
  push:
    branches:
      - 'develop'
      - 'master'
    tags:
      - '**'
  pull_request:
  workflow_dispatch:
    inputs:
      cmdstan-version:
        description: 'Version to test'
        required: false
        default: ''

jobs:
  get-cmdstan-version:
    # get the latest cmdstan version to use as part of the cache key
    name: grab version
    runs-on: ubuntu-latest
    steps:
      - name: Get CmdStan version
        id: check-cmdstan
        run: |
            if [[ "${{ github.event.inputs.cmdstan-version }}" != "" ]]; then
              echo "::set-output name=version::${{ github.event.inputs.cmdstan-version }}"
            else
                echo "::set-output name=version::$(python -c 'import requests;print(requests.get("https://api.github.com/repos/stan-dev/cmdstan/releases/latest").json()["tag_name"][1:])')"
            fi
    outputs:
      version: ${{ steps.check-cmdstan.outputs.version }}

  cmdstanpy:
    needs: get-cmdstan-version
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out github
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (python)
        run: |
          pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install codecov

      - name: Build wheel
        run: python setup.py bdist_wheel
        
      - name: Install wheel (Linux, macOS)
        if: matrix.os != 'windows-latest'
        run: pip install dist/*.whl
        
     
          
      - name: Run tests
        run: |
          mkdir run_tests
          cd run_tests
          pytest -v ../test --cov=../cmdstanpy

      - name: Run model with requirements-optional.txt
        run: |
          cd run_tests
          python -m pip install -r ../requirements-optional.txt
          python ../test/example_script.py

      - name: Submit codecov
        run: |
          cd run_tests
          codecov
